apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wordpress

resources:
  - wordpress.yaml
  - mariadb.yaml
  - httproute.yaml
  - cloudflared.yaml
  - secret.yaml
# generators:
#   - secret-generator.yaml
