apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: notifuse

resources:
  - namespace.yaml
  - postgres.yaml
  - notifuse.yaml
  - httproute.yaml
  - cloudflared.yaml

generators:
  - secret-generator.yaml
# If you want to use Backblaze B2 as medias storage, you must edit backblaze-cors.json and run the following command:
# b2 bucket update --cors-rules "$(<./backblaze-cors.json)" bucketName allPublic
# in case of b2 buffer overflow error, try: export COLUMNS=80 && export LINES=24
